import {Brand, Model, TestDrive, TestDriveStatus, Unit} from '~/services';
import {faker} from '@faker-js/faker';

faker.seed(42);
export const brands: Array<Brand> = Array.from({length: 13}, (_, i) => ({
  id: (i + 1).toString(),
  name: faker.vehicle.manufacturer(),
  description: faker.lorem.sentence(),
}));

export const models: Array<Model> = Array.from({length: 13}, (_, i) => ({
  id: (i + 1).toString(),
  name: faker.vehicle.model(),
  brandId: (i + 1).toString(),
  description: faker.lorem.sentence(),
  imageUrl: faker.image.urlLoremFlickr({
    category: 'car',
    width: 140,
    height: 140,
  }),
}));

// units
export const units: Array<Unit> = [
  {
    id: '1',
    unitNumber: 'A1',
    modelId: '1',
    year: 2020,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '123 Main St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '2',
    unitNumber: 'A2',
    modelId: '2',
    year: 2021,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '456 Elm St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '3',
    unitNumber: 'A3',
    modelId: '3',
    year: 2019,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '789 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '4',
    unitNumber: 'A4',
    modelId: '4',
    year: 2022,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '101 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '5',
    unitNumber: 'A5',
    modelId: '5',
    year: 2023,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '222 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '6',
    unitNumber: 'A6',
    modelId: '6',
    year: 2024,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '333 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '7',
    unitNumber: 'A7',
    modelId: '7',
    year: 2025,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '444 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '8',
    unitNumber: 'A8',
    modelId: '8',
    year: 2026,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '555 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '9',
    unitNumber: 'A9',
    modelId: '9',
    year: 2027,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '666 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '10',
    unitNumber: 'A10',
    modelId: '10',
    year: 2028,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '777 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '11',
    unitNumber: 'A11',
    modelId: '11',
    year: 2029,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '888 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '12',
    unitNumber: 'A12',
    modelId: '12',
    year: 2030,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '999 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '13',
    unitNumber: 'A13',
    modelId: '13',
    year: 2031,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '111 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '14',
    unitNumber: 'A14',
    modelId: '14',
    year: 2032,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '222 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '15',
    unitNumber: 'A15',
    modelId: '15',
    year: 2033,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '333 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '16',
    unitNumber: 'A16',
    modelId: '16',
    year: 2034,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '444 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '17',
    unitNumber: 'A17',
    modelId: '17',
    year: 2035,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '555 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '18',
    unitNumber: 'A18',
    modelId: '18',
    year: 2036,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '666 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '19',
    unitNumber: 'A19',
    modelId: '19',
    year: 2037,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '777 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '20',
    unitNumber: 'A20',
    modelId: '20',
    year: 2038,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '888 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
];

// 7 Test Drive Schedules
export const testDrives: Array<TestDrive> = [
  {
    id: '1',
    unitId: '1',
    userId: '1',
    dateFrom: new Date('2023-01-01'),
    dateTo: new Date('2023-01-05'),
    status: TestDriveStatus.PENDING,
    testDriveTypeId: '1',
    locationId: '1',
  },
  {
    id: '2',
    unitId: '2',
    userId: '2',
    dateFrom: new Date('2023-02-01'),
    dateTo: new Date('2023-02-05'),
    status: TestDriveStatus.CONFIRMED,
    testDriveTypeId: '2',
    locationId: '2',
  },
  {
    id: '3',
    unitId: '3',
    userId: '3',
    dateFrom: new Date('2023-03-01'),
    dateTo: new Date('2023-03-05'),
    status: TestDriveStatus.IN_PROGRESS,
    testDriveTypeId: '3',
    locationId: '3',
  },
  {
    id: '4',
    unitId: '4',
    userId: '4',
    dateFrom: new Date('2023-04-01'),
    dateTo: new Date('2023-04-05'),
    status: TestDriveStatus.COMPLETED,
    testDriveTypeId: '4',
    locationId: '4',
  },
  {
    id: '5',
    unitId: '5',
    userId: '5',
    dateFrom: new Date('2023-05-01'),
    dateTo: new Date('2023-05-05'),
    status: TestDriveStatus.CANCELLED,
    testDriveTypeId: '5',
    locationId: '5',
  },
  {
    id: '6',
    unitId: '6',
    userId: '6',
    dateFrom: new Date('2023-06-01'),
    dateTo: new Date('2023-06-05'),
    status: TestDriveStatus.NO_SHOW,
    testDriveTypeId: '6',
    locationId: '6',
  },
  {
    id: '7',
    unitId: '7',
    userId: '7',
    dateFrom: new Date('2023-07-01'),
    dateTo: new Date('2023-07-05'),
    status: TestDriveStatus.PENDING,
    testDriveTypeId: '7',
    locationId: '7',
  },
  {
    id: '8',
    unitId: '8',
    userId: '8',
    dateFrom: new Date('2023-08-01'),
    dateTo: new Date('2023-08-05'),
    status: TestDriveStatus.CONFIRMED,
    testDriveTypeId: '8',
    locationId: '8',
  },
  {
    id: '9',
    unitId: '9',
    userId: '9',
    dateFrom: new Date('2023-09-01'),
    dateTo: new Date('2023-09-05'),
    status: TestDriveStatus.IN_PROGRESS,
    testDriveTypeId: '9',
    locationId: '9',
  },
  {
    id: '10',
    unitId: '10',
    userId: '10',
    dateFrom: new Date('2023-10-01'),
    dateTo: new Date('2023-10-05'),
    status: TestDriveStatus.COMPLETED,
    testDriveTypeId: '10',
    locationId: '10',
  },
  {
    id: '11',
    unitId: '11',
    userId: '11',
    dateFrom: new Date('2023-11-01'),
    dateTo: new Date('2023-11-05'),
    status: TestDriveStatus.CANCELLED,
    testDriveTypeId: '11',
    locationId: '11',
  },
  {
    id: '12',
    unitId: '12',
    userId: '12',
    dateFrom: new Date('2023-12-01'),
    dateTo: new Date('2023-12-05'),
    status: TestDriveStatus.NO_SHOW,
    testDriveTypeId: '12',
    locationId: '12',
  },
];
