import {Brand, Model, TestDrive, TestDriveStatus, Unit} from '~/services';

export const brands: Array<Brand> = [
  {id: '1', name: 'Hyundai', description: 'Hyundai description'},
  {id: '2', name: 'Toyota', description: 'Toyota description'},
  {id: '3', name: 'Honda', description: 'Honda description'},
  {id: '4', name: 'Ford', description: 'Ford description'},
  {id: '5', name: 'Chevrolet', description: 'Chevrolet description'},
  {id: '6', name: 'Volkswagen', description: 'Volkswagen description'},
  {id: '7', name: 'Nissan', description: 'Nissan description'},
  {id: '8', name: 'Mazda', description: 'Mazda description'},
  {id: '9', name: 'Kia', description: 'Kia description'},
  {id: '10', name: 'Subaru', description: 'Subaru description'},
  {id: '11', name: 'Lexus', description: 'Lexus description'},
  {id: '12', name: 'Mitsubishi', description: 'Mitsubishi description'},
  {id: '13', name: 'Audi', description: 'Audi description'},
];

export const models: Array<Model> = [
  {
    id: '1',
    name: 'Sonata',
    brandId: '1',
    description:
      'The Hyundai Sonata is a mid-size car manufactured by Hyundai. The Sonata is marketed in many countries, including the United States, Canada, Mexico, Australia, and South Korea.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '2',
    name: 'Corolla',
    brandId: '2',
    description:
      'The Toyota Corolla is a line of subcompact and compact cars manufactured by Toyota. Introduced in 1966, the Corolla was the best-selling car in the world by 1974 and has since become one of the most popular and recognizable cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '3',
    name: 'Civic',
    brandId: '3',
    description:
      'The Honda Civic is a line of subcompact and compact cars manufactured by Honda. The Civic was introduced in 1972 and has since become one of the most popular and recognizable cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '4',
    name: 'Mustang',
    brandId: '4',
    description:
      'The Ford Mustang is an American automobile manufactured by Ford. The Mustang is a coupe or convertible car that was originally based on the Ford Falcon compact car.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '5',
    name: 'Silverado',
    brandId: '5',
    description:
      'The Chevrolet Silverado is a line of full-size and heavy-duty pickup trucks manufactured by General Motors. The Silverado was introduced in 1998 and has since become one of the most popular pickup trucks in the United States.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '6',
    name: 'Golf',
    brandId: '6',
    description:
      'The Volkswagen Golf is a compact hatchback car manufactured by Volkswagen. The Golf was introduced in 1974 and has since become one of the most popular cars in Europe and other parts of the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '7',
    name: 'Altima',
    brandId: '7',
    description:
      'The Nissan Altima is a mid-size car manufactured by Nissan. The Altima was introduced in 1992 and has since become one of the most popular cars in the United States.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '8',
    name: '3',
    brandId: '8',
    description:
      'The Mazda3 is a compact car manufactured by Mazda. The Mazda3 was introduced in 2003 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '9',
    name: 'Sorento',
    brandId: '9',
    description:
      'The Kia Sorento is a mid-size crossover SUV manufactured by Kia Motors. The Sorento was introduced in 2002 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '10',
    name: 'Forester',
    brandId: '10',
    description:
      'The Subaru Forester is a compact SUV manufactured by Subaru. The Forester was introduced in 1997 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '11',
    name: 'RX',
    brandId: '11',
    description:
      'The Lexus RX is a luxury crossover SUV manufactured by Lexus. The RX was introduced in 1998 and has since become one of the most popular luxury SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '12',
    name: 'Outlander',
    brandId: '12',
    description:
      'The Mitsubishi Outlander is a compact SUV manufactured by Mitsubishi Motors. The Outlander was introduced in 2001 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '13',
    name: 'Q5',
    brandId: '13',
    description:
      'The Audi Q5 is a compact luxury SUV manufactured by Audi. The Q5 was introduced in 2008 and has since become one of the most popular luxury SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '14',
    name: 'Camry',
    brandId: '2',
    description:
      'The Toyota Camry is a mid-size car manufactured by Toyota. The Camry was introduced in 1980 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '15',
    name: 'CR-V',
    brandId: '3',
    description:
      'The Honda CR-V is a compact SUV manufactured by Honda. The CR-V was introduced in 1997 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '16',
    name: 'Explorer',
    brandId: '4',
    description:
      'The Ford Explorer is a mid-size SUV manufactured by Ford. The Explorer was introduced in 1990 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '17',
    name: 'Tiguan',
    brandId: '5',
    description:
      'The Volkswagen Tiguan is a compact SUV manufactured by Volkswagen. The Tiguan was introduced in 2006 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '18',
    name: 'Jetta',
    brandId: '6',
    description:
      'The Volkswagen Jetta is a compact car manufactured by Volkswagen. The Jetta was introduced in 1992 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '19',
    name: 'Civic',
    brandId: '7',
    description:
      'The Honda Civic is a compact car manufactured by Honda. The Civic was introduced in 1989 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '20',
    name: 'Accord',
    brandId: '8',
    description:
      'The Honda Accord is a mid-size car manufactured by Honda. The Accord was introduced in 1993 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '21',
    name: 'Crosstour',
    brandId: '9',
    description:
      'The Kia Crosstour is a mid-size crossover SUV manufactured by Kia Motors. The Crosstour was introduced in 2012 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '22',
    name: 'Impreza',
    brandId: '10',
    description:
      'The Subaru Impreza is a compact car manufactured by Subaru. The Impreza was introduced in 1999 and has since become one of the most popular cars in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '23',
    name: 'RX 350',
    brandId: '11',
    description:
      'The Lexus RX 350 is a mid-size SUV manufactured by Lexus. The RX 350 was introduced in 2000 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '24',
    name: 'Outback',
    brandId: '12',
    description:
      'The Mitsubishi Outback is a mid-size SUV manufactured by Mitsubishi Motors. The Outback was introduced in 2001 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '25',
    name: 'Q7',
    brandId: '13',
    description:
      'The Audi Q7 is a mid-size SUV manufactured by Audi. The Q7 was introduced in 2008 and has since become one of the most popular SUVs in the world.',
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
];

// units
export const units: Array<Unit> = [
  {
    id: '1',
    unitNumber: 'A1',
    modelId: '1',
    year: 2020,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '123 Main St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '2',
    unitNumber: 'A2',
    modelId: '2',
    year: 2021,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '456 Elm St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '3',
    unitNumber: 'A3',
    modelId: '3',
    year: 2019,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '789 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '4',
    unitNumber: 'A4',
    modelId: '4',
    year: 2022,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '101 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '5',
    unitNumber: 'A5',
    modelId: '5',
    year: 2023,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '222 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '6',
    unitNumber: 'A6',
    modelId: '6',
    year: 2024,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '333 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '7',
    unitNumber: 'A7',
    modelId: '7',
    year: 2025,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '444 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '8',
    unitNumber: 'A8',
    modelId: '8',
    year: 2026,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '555 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '9',
    unitNumber: 'A9',
    modelId: '9',
    year: 2027,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '666 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '10',
    unitNumber: 'A10',
    modelId: '10',
    year: 2028,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '777 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '11',
    unitNumber: 'A11',
    modelId: '11',
    year: 2029,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '888 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '12',
    unitNumber: 'A12',
    modelId: '12',
    year: 2030,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '999 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '13',
    unitNumber: 'A13',
    modelId: '13',
    year: 2031,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '111 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '14',
    unitNumber: 'A14',
    modelId: '14',
    year: 2032,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '222 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '15',
    unitNumber: 'A15',
    modelId: '15',
    year: 2033,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '333 Oak St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '16',
    unitNumber: 'A16',
    modelId: '16',
    year: 2034,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '444 Pine St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '17',
    unitNumber: 'A17',
    modelId: '17',
    year: 2035,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '555 Maple St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '18',
    unitNumber: 'A18',
    modelId: '18',
    year: 2036,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '666 Cedar St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '19',
    unitNumber: 'A19',
    modelId: '19',
    year: 2037,
    availability: false,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '777 Birch St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
  {
    id: '20',
    unitNumber: 'A20',
    modelId: '20',
    year: 2038,
    availability: true,
    imageUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
    location: '888 Walnut St',
    mapUrl: `https://picsum.photos/140/140?random=${Math.random()}`,
  },
];

// 7 Test Drive Schedules
export const testDrives: Array<TestDrive> = [
  {
    id: '1',
    unitId: '1',
    userId: '1',
    dateFrom: new Date('2023-01-01'),
    dateTo: new Date('2023-01-05'),
    status: TestDriveStatus.PENDING,
    testDriveTypeId: '1',
    locationId: '1',
  },
  {
    id: '2',
    unitId: '2',
    userId: '2',
    dateFrom: new Date('2023-02-01'),
    dateTo: new Date('2023-02-05'),
    status: TestDriveStatus.CONFIRMED,
    testDriveTypeId: '2',
    locationId: '2',
  },
  {
    id: '3',
    unitId: '3',
    userId: '3',
    dateFrom: new Date('2023-03-01'),
    dateTo: new Date('2023-03-05'),
    status: TestDriveStatus.IN_PROGRESS,
    testDriveTypeId: '3',
    locationId: '3',
  },
  {
    id: '4',
    unitId: '4',
    userId: '4',
    dateFrom: new Date('2023-04-01'),
    dateTo: new Date('2023-04-05'),
    status: TestDriveStatus.COMPLETED,
    testDriveTypeId: '4',
    locationId: '4',
  },
  {
    id: '5',
    unitId: '5',
    userId: '5',
    dateFrom: new Date('2023-05-01'),
    dateTo: new Date('2023-05-05'),
    status: TestDriveStatus.CANCELLED,
    testDriveTypeId: '5',
    locationId: '5',
  },
  {
    id: '6',
    unitId: '6',
    userId: '6',
    dateFrom: new Date('2023-06-01'),
    dateTo: new Date('2023-06-05'),
    status: TestDriveStatus.NO_SHOW,
    testDriveTypeId: '6',
    locationId: '6',
  },
  {
    id: '7',
    unitId: '7',
    userId: '7',
    dateFrom: new Date('2023-07-01'),
    dateTo: new Date('2023-07-05'),
    status: TestDriveStatus.PENDING,
    testDriveTypeId: '7',
    locationId: '7',
  },
  {
    id: '8',
    unitId: '8',
    userId: '8',
    dateFrom: new Date('2023-08-01'),
    dateTo: new Date('2023-08-05'),
    status: TestDriveStatus.CONFIRMED,
    testDriveTypeId: '8',
    locationId: '8',
  },
  {
    id: '9',
    unitId: '9',
    userId: '9',
    dateFrom: new Date('2023-09-01'),
    dateTo: new Date('2023-09-05'),
    status: TestDriveStatus.IN_PROGRESS,
    testDriveTypeId: '9',
    locationId: '9',
  },
  {
    id: '10',
    unitId: '10',
    userId: '10',
    dateFrom: new Date('2023-10-01'),
    dateTo: new Date('2023-10-05'),
    status: TestDriveStatus.COMPLETED,
    testDriveTypeId: '10',
    locationId: '10',
  },
  {
    id: '11',
    unitId: '11',
    userId: '11',
    dateFrom: new Date('2023-11-01'),
    dateTo: new Date('2023-11-05'),
    status: TestDriveStatus.CANCELLED,
    testDriveTypeId: '11',
    locationId: '11',
  },
  {
    id: '12',
    unitId: '12',
    userId: '12',
    dateFrom: new Date('2023-12-01'),
    dateTo: new Date('2023-12-05'),
    status: TestDriveStatus.NO_SHOW,
    testDriveTypeId: '12',
    locationId: '12',
  },
];
